### PR TITLE
simplify build

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by slang25** [comment]
You could chose to omit `IsTestProject` from your projects, as referencing `Microsoft.NET.Test.Sdk` will set it to true for you, it will default to false otherwise.

**Comment by adamralph** [comment]
@slang25 adding it explicitly to non-test projects gets rid of this message:

> Skipping running test for project C:\code\adamralph\minver\targets\Targets.csproj. To run tests with dotnet test add "<IsTestProject>true<IsTestProject>" property to project file.

Or at least, it will when this bug fix is released: https://github.com/Microsoft/vstest/issues/1866 😉

**Comment by adamralph** [comment]
> referencing `Microsoft.NET.Test.Sdk` will set it to true for you

@slang25 I did not know that though. That's good to know, thanks. I'll remove it from the test projects.

Something seems off here. We shouldn't have to add it to non-test projects to get rid of that silly message.

**Comment by slang25** [comment]
I hadn't realised you got a message in the log either.

I feel the message should be off by default, or at least be possible to switch off. It happens here:
https://github.com/Microsoft/vstest/blob/37696768786ef1018f0b4499eab9ca27af141057/src/Microsoft.TestPlatform.Build/Microsoft.TestPlatform.targets#L55

**Comment by adamralph** [comment]
@slang25 see https://github.com/Microsoft/vstest/pull/1867/files#r240614971

**Comment by slang25** [comment]
Nice, I just arrived at the same conclusion myself, you are quicker than me 😄

**Pull request merged**
