### PR TITLE
log inputs and outputs

### LINKED ISSUE #147: Output all properties at detailed level
_As suggested by @blairconrad: https://github.com/adamralph/minver/issues/146#issuecomment-444124896._

### PR DESCRIPTION
**Pull request by adamralph**
Closes #147

### CODE REVIEW

**Comment by adamralph** [comment]
@blairconrad how does this look WRT https://github.com/adamralph/minver/issues/147 ?

You mentioned in https://github.com/adamralph/minver/issues/146#issuecomment-444124896 that it should also also log the nupkg filename, what you referred to as `PackageFilenameVersion`, but that is out MinVer's control. All it can do is log the properties that it sets. The derivation of the nupkg filename is done by other targets in the .NET SDK and is standard behaviour. Although there could even be other custom targets injected into the pipeline which alter it, and MinVer has no way to know about those.

**Comment by adamralph** [comment]
@bording do you have any view on this?

**Comment by blairconrad** [comment]
It looks good, @adamralph. I understand that the filename is out of your control (I did not then). Thanks!

**Comment by adamralph** [comment]
Released in [beta 2](https://www.nuget.org/packages/MinVer/1.0.0-beta.2).

**Pull request merged**
