### PR TITLE
change message about min major minor from 'redundant' to 'ignoring'

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by adamralph** [comment]
@bording how does this look?

**Comment by adamralph** [comment]
One thing to bear in mind is that the minimum _version_ is never specified. Only a minimum major minor range. I guess the minimum version would be something like `major.minor.0-0` but it would be quite odd to see that in the logs. What if the message said something like this?

> The calculated version {version} satisfies the minimum major minor {minMajorMinor}.

**Comment by bording** [comment]
@adamralph That seems fine as well. It's just that this whole scenario doesn't fit my mental model of how I think about that property at all, which is why I'm having a disconnect here.

**Comment by adamralph** [comment]
@bording OK, I've changed it to that last proposal for now. If you have some more thoughts on this, please let me know.

**Comment by adamralph** [comment]
Oops, forgot to change the commit message. 🤷‍♂️

**Comment by adamralph** [comment]
Released in [beta 2](https://www.nuget.org/packages/MinVer/1.0.0-beta.2).

**Pull request merged**
