### PR TITLE
Redundant min major minor

### LINKED ISSUE #151: debug/detailed level message when MinVerMajorMinor is redundant
`MinVerMajorMinor` is redundant when a tag is found with a higher version.

Kudos to @cameronfletcher for suggesting this.

### PR DESCRIPTION
**Pull request by adamralph**
Closes #151

### CODE REVIEW

**Comment by bording** [comment]
Why is this needed? Given that the property is a "minumum" why do you need to warn?

Ah, but It is a debug level entry, so I guess most people won't see it.

**Comment by adamralph** [comment]
@bording it's effectively the message you described in https://github.com/adamralph/minver/issues/151#issuecomment-445371035

**Comment by bording** [comment]
The distinction I see between what I mentioned before and this is that by saying it's redundant, that implies it should be removed. However, given that the the property is a minimum, there's nothing wrong with having it be there. It isn't redundant, it's expected that the calculation might choose something higher than the minimum that's been specified.

**Comment by adamralph** [comment]
Under normal usage, once a higher version is chosen, the property will never have any effect again since the tag used to choose the higher version will always be found in the history.

I guess where that falls down is if tags are removed, or an older tag is created in front of a newer tag. To me that is an invalid workflow, but it's difficult to second guess the exotic usage that might come to exist. To be sure, I'll take the mention of redundancy out.

**Comment by adamralph** [comment]
Released in [beta 2](https://www.nuget.org/packages/MinVer/1.0.0-beta.2).

**Pull request merged**
