### PR TITLE
fix target injection for clean and pack

### LINKED ISSUE #675: Invalid order with NuGet pack leading to invalid outputs
Hey, 
Thank you for MinVer. I'm starting to use it in all my projects and it simplifies a lot what I was doing manually! 👍 

## Version(s)

`2.5.0`

## Problem

I'm developing a tooling that simplifies the whole build/publish process for .NET libraries/apps on GitHub ([dotnet-releaser](https://github.com/xoofx/dotnet-releaser)) and I discovered a weird behavior while using MinVer on a multi-targeting version (It seems that it doesn't affect packages with only one target framework).

I'm calling msbuild directly with a special logger from which I can extract results from msbuild and I discovered that the version used to name output files in msbuild with MinVer when packing is wrong. 

For example, below, you have a screenshot of msbuild log:

image

It is supposed to create the package `Tomlyn.0.11.0.nupkg` and the pack command does it, but actually, when you look in the details, msbuild will think that it needs to generate `Tomlyn.1.0.0.nupkg` and will always re-run even if you build it just before.

Reason is that the file output is calculated in the target `_GetOutputItemsFromPack` which called by `_CalculateInputsOutputsForPack` (code [here](https://github.com/NuGet/NuGet.Client/blob/352ba94f120f1a3481a2cae6190a1947a85a160f/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L178-L194)) but MinVer runs only just before `GenerateNuspec` (as you can see in the screenshot above), but not before `_GetOutputItemsFromPack`.

## Expected behaviour

NuGet msbuild tasks should get the version calculated from MinVer in order to correctly compute output packages.

## Actual behaviour

NuGet is originally thinking that the version is `1.0.0` instead the version calculated by MinVer. If you run multiple times NuGet pack with MinVer, it will always have to repack the package thinking that it doesn't exist (because 1.0.0 is not created in the end)

## Workarounds

No great workaround as I would have to make my tooling MinVer aware to force MinVer to insert before `_GetOutputItemsFromPack`.

## Fix Suggestion

Add a msbuild dependency to `_GetOutputItemsFromPack` instead of only `GenerateNuSpec`. 
Hacking MinVer locally and it is now correctly generating the correct versions:

image

I will make a PR with this suggestion fix.

### PR DESCRIPTION
**Pull request by adamralph**
relates to #682
relates to #683

### CODE REVIEW

**Comment by adamralph** [comment]
I want to add tests for #682 and #683 before merging this.

**Comment by bording** [comment]
I've been away from GitHub for the past two weeks, so I'm just catching up with things now.

Looking over the issues and this PR, adding the `MinVer` target to `GenerateNuspecDependsOn` seems like a good fix for #682.

For #683, I think we might want to tweak this a bit more, though.

The `_CleanPackageFiles` target has a `'$(GeneratePackageOnBuild)' == 'true'` condition, so it only runs when someone has set that to true, which is not the default.

The change here means that MinVer will be running during clean even when a package hasn't been built.

One option to fix this would be to add another target, something like:
```
<Target Name="_MinVerClean" BeforeTargets="Clean" DependsOnTargets="MinVer" Condition="'$(GeneratePackageOnBuild)' == 'true'" />
```

I believe that should continue to let the package be cleaned properly, but not invoke MinVer unnecessarily. It couldn't hurt to confirm that via a build log file, though.

**Comment by adamralph** [comment]
> The change here means that MinVer will be running during clean even when a package hasn't been built.

@bording good catch! Your suggested change sounds good. I'll re-open https://github.com/adamralph/minver/issues/683 for now.

**Comment by adamralph** [comment]
raised https://github.com/adamralph/minver/pull/704

**Pull request merged**
